[platformio]
src_dir = .

[env:t-keyboard-s3-pro]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
board_build.f_cpu = 240000000L
board_build.flash_type=qio
board_build.psram_type=opi
board_build.memory_type=qio_opi
board_upload.flash_size = 16MB

build_flags =
    # -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.0
    lbuque/ButtonSense @ ^1.0.0
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    T-Keyboard-S3-Pro-Library=symlink://../../../

data_dir = data
